### PR TITLE
Apple page

### PR DESCRIPTION
**Pull request by WCanirinka**
I am requesting for a review for the completion of this project. Thank you

### CODE REVIEW

**Comment by WCanirinka** [comment]
Activated stickler.

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @WCanirinka :wave: 

Nice job so far; you have really done well but unfortunately, you need to turn ON stickler on this repo.

- [x] Properly setup stickler. _Refer to [this guide](https://github.com/microverseinc/linters-config/tree/master/css) for guidelines on how to properly setup stickler._

**Kindly submit another code review request after fixing the linting issue.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by WCanirinka** [comment]
I have activated stickler. I request for a new review

**Comment by ebukaume** [comment]
> I have activated stickler. I request for a new review

The check tab is still registering 0 and you should have this kind of image below.

stickler-checks

**Comment by WCanirinka** [comment]
Now it is enabled. I request for a new review

**Comment by ebukaume** [comment]
## Approved! :champagne: 

Hi @WCanirinka :wave: 

**Congratulations! :+1: . You can go ahead and merge this branch.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
